source 'https://github.com/CocoaPods/Specs.git'

target 'CGLCollectionView', :exclusive => true do
  pod "CGLCollectionView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CGLCollectionView", :path => "../"

  
end
